name: Build Win

on:
  push

jobs:

  build_on_windows:

    runs-on: windows-2022

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: DIR
        run: dir
      
      - name: Test R
        run: Rscript -e "install.packages("Rcpp")"

      - name: Test cmake
        run: cmake
      
      - name: CMake Configure
        run: cmake -S . -B build
